### PR TITLE
Added javac source and target versions

### PR DESCRIPTION
**Pull request by migesok**
To ensure that a compatible with JVM 7 bytecode is produced.
Current version of the library is built against Java 8:
http://search.maven.org/remotecontent?filepath=com/github/michaelpisula/akka-persistence-inmemory_2.10/0.1.1/akka-persistence-inmemory_2.10-0.1.1.jar

>  javap -verbose akka.persistence.journal.inmemory.InMemoryJournal | grep "major"
>   major version: 52

Which cause errors on JVM 7:

java.lang.UnsupportedClassVersionError: akka/persistence/journal/inmemory/InMemoryJournal : Unsupported major.minor version 52.0

It would be great to use akka-journal-inmemory with JVM 7 as Java 8 is not widely used yet and I believe most of the production Scala-Akka code is ran against JVM 7.

### CODE REVIEW

**Comment by michaelpisula** [comment]
Thanks for reporting and fixing =)

**Comment by michaelpisula** [comment]
I will publish the fixed version later today as 0.1.2

**Comment by michaelpisula** [comment]
0.1.2 released, should be on maven central soon

**Comment by migesok** [comment]
Thanks for your quick response!
Sad thing 0.1.2 in maven central is still compiled for JVM 8:
http://search.maven.org/remotecontent?filepath=com/github/michaelpisula/akka-persistence-inmemory_2.10/0.1.2/akka-persistence-inmemory_2.10-0.1.2.jar

I have made a foul job testing the changes only with the "compile" target.
I see you have fixed that in 0.2.0 but it is only for Scala 2.11 which leaves me out in the cold as not all of my deps have been compiled for it.
Pull request with cross-build so you can publish the library for 2.10 and 2.11:
https://github.com/michaelpisula/akka-journal-inmemory/pull/3

**Comment by michaelpisula** [comment]
My fault, I should have realized that the problems with target while publishing 0.2.0 should have appeared in 0.1.2 as well, if sbt had pulled in the changes. Still no idea why sbt did not, it did pull in the updated version number, very strange...

The cross-build is a great idea and should fix that too. Not sure if there will be problems with 0.2.0 for users using Akka < 2.3.4 though. I might also create a 0.1.3 for those.

**Comment by migesok** [comment]
I'm going to migrate to 2.3.4 soon so it is not an issue for me.
Akka persistence stuff is not stable yet and changes often so keeping up with it is generally a good idea.

**Pull request merged**
